app/models/customer.py
from typing import TYPE_CHECKING, List, Optional
from datetime import datetime, timezone
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import Integer, String, Text, ForeignKey, DateTime, event
from app.utilities.history_meta import Versioned
from app import db

if TYPE_CHECKING:
    from app.models.address import Address
    from app.models.user import User


class Customer(Versioned, db.Model):
    __tablename__ = "customer"
    use_mapper_versioning = True  # Creates a version_id column through the Versioned mixin.

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    related_username: Mapped[str] = mapped_column(String(255), default="System")
    create_date: Mapped[datetime] = mapped_column(DateTime, default=datetime.now(timezone.utc))

    addresses: Mapped[List["Address"]] = relationship("Address", back_populates="customer", cascade="all, delete-orphan")
    phone_numbers: Mapped[List["Telephone"]] = relationship("Telephone", back_populates="customer", cascade="all, delete-orphan")
    emails: Mapped[List["Email"]] = relationship("Email", back_populates="customer", cascade="all, delete-orphan")
    memos: Mapped[Optional[List["Memo"]]] = relationship("Memo", back_populates="customer", cascade="all, delete-orphan")

    def __repr__(self):
        return (f"<Customer id: {self.id!r}, "
                f"name: {self.name!r}>, "
                f"related_username: {self.related_username!r}>, "
                f"create_date: {self.create_date!r}> ")


class Telephone(Versioned, db.Model):
    __tablename__ = "telephone"
    use_mapper_versioning = True  # Creates a version_id column through the Versioned mixin.

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    phone_number: Mapped[str] = mapped_column(String(255))
    related_username: Mapped[str] = mapped_column(String(255), default="System")
    customer_id: Mapped[int] = mapped_column(ForeignKey("customer.id", ondelete="CASCADE"))

    customer: Mapped["Customer"] = relationship("Customer", back_populates="phone_numbers")

    def __repr__(self):
        return (f"<Telephone id: {self.id!r}, "
                f"phone_number: {self.phone_number!r}, "
                f"related_username: {self.related_username!r}>, "
                f"customer_id: {self.customer_id!r}>")


# Strip parentheses and dashes.
@event.listens_for(Telephone.phone_number, 'set', retval=True)
def format_phone_number(target, value, oldvalue, initiator):
    if value is not None:
        char_to_remove = ["(", ")", "-"]
        for char in char_to_remove:
            value = value.replace(char, "")
    return value


class Email(Versioned, db.Model):
    __tablename__ = "email"
    use_mapper_versioning = True  # Creates a version_id column through the Versioned mixin.

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    email: Mapped[str] = mapped_column(String(255))
    related_username: Mapped[str] = mapped_column(String(255), default="System")
    customer_id: Mapped[int] = mapped_column(ForeignKey("customer.id", ondelete="CASCADE"))

    customer: Mapped["Customer"] = relationship("Customer", back_populates="emails")

    def __repr__(self):
        return (f"<Email id: {self.id!r}, "
                f"email: {self.email!r}, "
                f"related_username: {self.related_username!r}>, "
                f"customer_id: {self.customer_id!r}>")


class Memo(db.Model):
    __tablename__ = "memo"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    memo_content: Mapped[str] = mapped_column(Text)
    create_date: Mapped[datetime] = mapped_column(DateTime, default=datetime.now(timezone.utc))
    related_username: Mapped[str] = mapped_column(String(255), default="System")
    customer_id: Mapped[int] = mapped_column(ForeignKey("customer.id", ondelete="CASCADE"))
    user_id: Mapped[Optional[int]] = mapped_column(ForeignKey("user.id"))

    customer: Mapped[Optional["Customer"]] = relationship("Customer", back_populates="memos")
    user: Mapped[Optional["User"]] = relationship("User", back_populates="memos")

    def __repr__(self):
        return (f"<Memo id: {self.id!r}, "
                f"create_date: {self.create_date!r}, "
                f"related_username: {self.related_username!r}>, "
                f"customer_id: {self.customer_id!r}, "
                f"user_id: {self.user_id!r}, "
                f"memo_content: {self.memo_content!r}>")

app/customer/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TelField, SelectField, EmailField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, Email, Length


def select_field_choices_state():
    choices = [("", ""), ("AL", "AL"), ("AK", "AK"), ("AZ", "AZ"), ("AR", "AR"), ("CA", "CA"),
               ("CO", "CO"), ("CT", "CT"), ("DE", "DE"), ("DC", "DC"), ("FL", "FL"), ("GA", "GA"), ("HI", "HI"),
               ("ID", "ID"), ("IL", "IL"), ("IN", "IN"), ("IA", "IA"), ("KS", "KS"), ("KY", "KY"), ("LA", "LA"),
               ("ME", "ME"), ("MD", "MD"), ("MA", "MA"), ("MI", "MI"), ("MN", "MN"), ("MS", "MS"), ("MO", "MO"),
               ("MT", "MT"), ("NE", "NE"), ("NV", "NV"), ("NH", "NH"), ("NJ", "NJ"), ("NM", "NM"), ("NY", "NY"),
               ("NC", "NC"), ("ND", "ND"), ("OH", "OH"), ("OK", "OK"), ("OR", "OR"), ("PA", "PA"), ("RI", "RI"),
               ("SC", "SC"), ("SD", "SD"), ("TN", "TN"), ("TX", "TX"), ("UT", "UT"), ("VT", "VT"), ("VA", "VA"),
               ("WA", "WA"), ("WV", "WV"), ("WI", "WI"), ("WY", "WY")]
    return choices


def select_to_add_contact_choices():
    choices = [("", ""),
               ("otherPhone", "Other Phone"),
               ("otherEmail", "Other Email")]
    return choices


class customerForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    street = StringField('Street', validators=[DataRequired()])
    city = StringField('City', validators=[DataRequired()])
    state = SelectField('State', choices=select_field_choices_state(), validators=[DataRequired()])
    zip = IntegerField('Zip', validators=[DataRequired()])
    phone_number = TelField('Phone Number', id='phoneNumber', name='Phone Number', validators=[DataRequired(), Length(min=13, max=13)])
    email = EmailField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Submit', id='customerFormButton')


class addContactInfoForm(FlaskForm):
    select_to_add = SelectField('Create Contact', choices=select_to_add_contact_choices())
    other_phone_number = TelField('Other Phone', id='otherPhone', validators=[DataRequired(), Length(max=13)])
    other_email = EmailField('Other Email', id="otherEmail", validators=[DataRequired(), Email()])


class addMemoForm(FlaskForm):
    memo_content = TextAreaField('Memo Content', id='memoContent', validators=[DataRequired(), Length(min=1)])

app/customer/__init__.py
from flask import Blueprint

bp = Blueprint('customer', __name__)

from app.customer import routes

app/customer/routes.py
from flask import render_template, current_app, request, g, flash, session, jsonify
from flask_login import current_user, login_required
from datetime import datetime, timezone
from app import db
from app.customer import bp
from app.utilities.utilities import format_date_local
from app.models.customer import Customer, Telephone, Email, Memo
from app.models.address import Address
from app.models.user import User
from app.customer.forms import customerForm, addContactInfoForm, addMemoForm


##############################################################################################################
#### Table Index View of All Customers
##############################################################################################################
@bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    # Reset search query.
    session.pop('search_tag', default=None)
    session['thisRoutePrevPage'] = request.url

    page = request.args.get('page', 1, type=int)
    customers = db.paginate(db.select(Customer),
                            page=page,
                            per_page=current_app.config['CUSTOMERS_PER_PAGE'],
                            )

    # Pagination endpoint for macro
    endpoint = 'customer.index'

    return render_template('customer/index.html.j2',
                           customers=customers,
                           endpoint=endpoint,
                           )


##############################################################################################################
#### Add Customer
##############################################################################################################
@bp.route('/add/', methods=['GET', 'POST'])
@login_required
def add_customer():
    form = customerForm()
    if form.validate_on_submit():
        new_customer = Customer(name=form.name.data,
                                related_username=current_user.username,
                                create_date=datetime.now(timezone.utc),
                                )
        new_address = Address(street=form.street.data,
                              city=form.city.data,
                              state=form.state.data,
                              zip=form.zip.data,
                              related_username=current_user.username,
                              )

        new_phone = Telephone(phone_number=form.phone_number.data,
                              related_username=current_user.username,
                              )
        new_email = Email(email=form.email.data,
                          related_username=current_user.username,
                          )

        new_customer.addresses.append(new_address)
        new_customer.phone_numbers.append(new_phone)
        new_customer.emails.append(new_email)

        db.session.add(new_customer)
        db.session.commit()
        flash('New Customer Added')
        return jsonify(status='200 OK', message='Customer add successful')

    return render_template('customer/new_customer.html.j2',
                           form=form,
                           Customer=Customer,
                           )


##############################################################################################################
#### Customer Summary View
##############################################################################################################
@bp.route('/<int:Id>/', methods=['POST', 'GET'])
@login_required
def detail(Id):
    form = customerForm()
    addContactForm = addContactInfoForm()
    createNewMemoForm = addMemoForm()
    customer = db.get_or_404(Customer, Id)

    memos = db.session.execute(db.select(Memo, User)
                               .join(Memo.user)
                               .where(Memo.customer_id == Id)
                               .order_by(Memo.create_date.desc())).all()

    thisRoutePrevPage = session.get('thisRoutePrevPage')

    if request.method == 'GET':
        # Pre-fill forms
        form.name.data = customer.name
        form.street.data = customer.addresses[0].street
        form.city.data = customer.addresses[0].city
        form.state.data = customer.addresses[0].state
        form.zip.data = customer.addresses[0].zip
        form.phone_number.data = customer.phone_numbers[0].phone_number
        form.email.data = customer.emails[0].email
        if (len(customer.phone_numbers) > 1):
            addContactForm.other_phone_number.data = customer.phone_numbers[1].phone_number
        if (len(customer.emails) > 1):
            addContactForm.other_email.data = customer.emails[1].email

        customer_create_date = format_date_local('', customer.create_date, '')

    return render_template('customer/customer_navbar.html.j2',
                           customer=customer,
                           form=form,
                           addContactForm=addContactForm,
                           createNewMemoForm=createNewMemoForm,
                           thisRoutePrevPage=thisRoutePrevPage,
                           customer_create_date=customer_create_date,
                           memos=memos,
                           format_date_local=format_date_local,
                           )


##############################################################################################################
#### Edit Customer - Also handles deletion of other contact info (otherPhone, otherEmail).
##############################################################################################################
@bp.route('/<int:Id>/edit/', methods=['POST'])
@login_required
def edit(Id):
    form = customerForm()
    addContactForm = addContactInfoForm()
    customer = db.get_or_404(Customer, Id)
    username = current_user.username

    if form.validate_on_submit():
        if customer.name != form.name.data:
            customer.name = form.name.data
            customer.related_username = username
        if customer.addresses[0].street != form.street.data:
            customer.addresses[0].street = form.street.data
            customer.addresses[0].related_username = username
        if customer.addresses[0].city != form.city.data:
            customer.addresses[0].city = form.city.data
            customer.addresses[0].related_username = username
        if customer.addresses[0].state != form.state.data:
            customer.addresses[0].state = form.state.data
            customer.addresses[0].related_username = username
        if customer.addresses[0].zip != form.zip.data:
            customer.addresses[0].zip = form.zip.data
            customer.addresses[0].related_username = username
        if customer.phone_numbers[0].phone_number != form.phone_number.data:
            customer.phone_numbers[0].phone_number = form.phone_number.data
            customer.phone_numbers[0].related_username = username
        if customer.emails[0].email != form.email.data:
            customer.emails[0].email = form.email.data
            customer.emails[0].related_username = username

        # Add/edit other_phone.
        if (len(customer.phone_numbers) <= 1 and request.form.get('other_phone_number')):
            addOtherPhone = Telephone(phone_number=request.form.get('other_phone_number'),
                                      related_username=current_user.username,
                                      )
            customer.phone_numbers.append(addOtherPhone)

        if (len(customer.phone_numbers) > 1):
            if customer.phone_numbers[1].phone_number != addContactForm.other_phone_number.data:
                customer.phone_numbers[1].phone_number = addContactForm.other_phone_number.data
                customer.phone_numbers[1].related_username = username

        # Add/edit other_email.
        if (len(customer.emails) <= 1 and request.form.get('other_email')):
            addOtherEmail = Email(email=request.form.get('other_email'),
                                  related_username=current_user.username,
                                  )
            customer.emails.append(addOtherEmail)

        if (len(customer.emails) > 1):
            if customer.emails[1].email != addContactForm.other_email.data:
                customer.emails[1].email = addContactForm.other_email.data
                customer.emails[1].related_username = username

        # Handle deletion of other contact info
        if 'deleteOtherContactInfo' in request.form and request.form['deleteOtherContactInfo'] == 'true':
            # Delete otherPhone or otherEmail.
            if 'otherPhone' in request.form and len(customer.phone_numbers) > 1:
                other_phone_to_delete = db.session.get(Telephone, customer.phone_numbers[1].id)
                if other_phone_to_delete:
                    db.session.delete(other_phone_to_delete)

            if 'otherEmail' in request.form and len(customer.emails) > 1:
                other_email_to_delete = db.session.get(Email, customer.emails[1].id)
                if other_email_to_delete:
                    db.session.delete(other_email_to_delete)

        db.session.add(customer)
        db.session.commit()
        flash('Your changes have been saved.')
        return jsonify(status='200 OK', message='Customer edit successful')

    # If form did not validate, return an error response
    flash('Form validation failed. Your changes were not saved.')
    return jsonify(status='400 Bad Request', error='Form validation failed')


##############################################################################################################
#### Delete Customer
##############################################################################################################
@bp.route('/<int:Id>/delete/', methods=['POST'])
@login_required
def delete_customer(Id):
    customerID = db.get_or_404(Customer, Id)
    if customerID:
        db.session.delete(customerID)
        db.session.commit()
        flash('Customer deleted')

app/templates/customer/_audit_log.html.j2
{% block content %}


<div class="container text-center mb-5 mt-5">
    <span class="title"><h1>{% block title %} Audit Log {% endblock %}</h1></span>
</div>


<div class="scrollableTableDiv">
    <table class="table table-striped table-hover table-bordered fixed-header-table">
        <thead class="sticky-header">
            <tr class="text-center">
                <th>Modified On</th>
                <th>Username</th>
                <th>Version</th>
                <th>Action/Field</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody id="auditLog">
        {% for audit_log in audit_logs %}
                <tr class="text-center">
                    {% set modified_on = format_date_local('', audit_log.modified_on, '') %}
                    <td>{{ modified_on }}</td>
                    <td>{{ audit_log.username }}</td>
                    <td>{{ audit_log.version }}</td>
                    <td>{{ audit_log.transaction_type }} / {{ audit_log.model }}</td>
                    {% if audit_log.model == "Telephone" %}
                    {% set audit_log_formatted_phone = format_phone_number(audit_log.details) %}
                    <td>{{ audit_log_formatted_phone }}</td>
                    {% else %}
                    <td>{{ audit_log.details }}</td>
                    {% endif %}
                </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


<div class="container text-center mt-5">
    <button type="button" class="btn btn-primary closeButton" id="auditCloseButton"
        data-prev="{{thisRoutePrevPage}}">Close</button>
</div>


{% endblock content %}

app/templates/customer/_documents.html.j2
{% block content %}

<div class="container text-center mb-5 mt-5">
    <span class="title"><h1>{% block title %} Documents {% endblock %}</h1></span>
</div>


{% endblock %}

app/templates/customer/_memos.html.j2
{% from "includes/macros.html.j2" import render_field %}


{% block content %}


<div class="memo-grid-wrapper">

    <div class="memo-page-title container text-center mt-5">
        <span class="title">
            <h1>{% block title %} Memos {% endblock %}</h1>
        </span>
    </div>


    <div class="scrollableTableDiv">
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr class="text-center">
                    <th>Memo Create Date</th>
                    <th>User</th>
                    <th>Memo Content</th>
                </tr>
            </thead>
            <tbody id="customers">
                {% for memo in memos %}
                <tr class="text-center align-middle">
                    {% set create_date = format_date_local('', memo[0].create_date, '') %}
                    <td>{{ create_date }}</td>
                    <td>{{ memo[1].username }}</td>
                    <td class="memo-content-td">{{ memo[0].memo_content }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <form action="" method="POST" class="create-memo-form" id="createMemoForm" novalidate>
        <div class="mb-3 memoFormDiv">
            {{ form.hidden_tag() }}
            {{ render_field(createNewMemoForm.memo_content) }}
        </div>
    </form>


    <div class="memo-submit-btn">
        <button type="button" class="btn btn-primary" form="create-memo-form"
            data-memo="{{ url_for('customer.create_new_memo', Id=customer.id)}}" id="newMemoFormButton">Submit
        </button>
    </div>

    <div class="memo-close-button container text-center mt-5">
        <button type="button" class="btn btn-primary closeButton" id="memoCloseButton"
            data-prev="{{thisRoutePrevPage}}">Close</button>
    </div>

</div> <!-- End of display grid wrapper -->


{% endblock %}

app/templates/customer/_summary.html.j2
{% from "includes/macros.html.j2" import render_field %}


{% block content %}

<div class="container text-center mb-5 mt-5">
    <span class="title"><h1>{% block title %} Summary {% endblock %}</h1></span>
</div>



<div class="row mt-5">
    <div class="col-sm-6 mb-3 mb-sm-0">
        <form action="" method="POST" class="needs-validation" id="editCustomerForm" novalidate>
        <div class="card">
            <div class="card-header text-center">
                <h5><b>Name & Address</b></h5>
            </div>
            <div class="card-body py-1">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ render_field(form.name, disabled="true")}}</li>
                    <li class="list-group-item">{{ render_field(form.street, disabled="true")}}</li>
                    <li class="list-group-item">{{ render_field(form.city, disabled="true")}}</li>
                    <li class="list-group-item">{{ render_field(form.state, disabled="true")}}</li>
                    <li class="list-group-item">{{ render_field(form.zip, disabled="true")}}</li>
                </ul>
            </div>
        </div>

        <div class="card mt-3">
            <div class="card-header text-center">
                <h5><b>Created On</b></h5>
            </div>
            <div class="card-body py-1">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ customer_create_date }}</li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Second column -->
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header text-center">
                <h5><b>Contact</b></h5>
            </div>
            <div class="card-body py-1">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        {{ render_field(form.phone_number, maxlength="13", disabled="true")}}
                    </li>
                    <li class="list-group-item">{{ render_field(form.email, disabled="true")}}</li>
                </ul>
            </div>
        </div>
        </form>

        <form action="" method="POST" class="needs-validation" id="otherCustomerForm" novalidate>
        <div class="card mt-3">
            <div class="card-header text-center">
                <h5><b>Other Contact</b></h5>
            </div>
            <div class="card-body py-1">
                <ul class="list-group list-group-flush" id="otherCustomerFormUL">
                    {% if addContactForm.other_phone_number.data %}
                    <li class="list-group-item">
                        {{ render_field(addContactForm.other_phone_number, maxlength="13", disabled="true")}}
                    </li>
                    {% endif %}
                    {% if addContactForm.other_email.data %}
                    <li class="list-group-item">{{ render_field(addContactForm.other_email, disabled="true")}}</li>
                    {% endif %}
                    <li class="list-group-item" id="selectContact">
                        {{ render_field(addContactForm.select_to_add, disabled="true")}}
                    </li>
                </ul>
            </div>
        </div>
        </form>

    </div>
</div><!-- End of first row -->


<div class="container text-center mt-5">
    <button type="button" class="btn btn-primary" id="editButton" form="editCustomerForm otherCustomerForm"
        data-edit="{{ url_for('customer.edit', Id=customer.id)}}">Edit</button>
    <button type="button" class="btn btn-primary" id="closeButton" data-prev="{{thisRoutePrevPage}}">Close</button>
</div>

{% endblock %}

<!-- Page specific Javascripts -->
{% block extra_js %}
    <script src="{{ url_for('static', filename='assets/js/inputValidation.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
{% endblock extra_js %}

app/templates/customer/customer_detail.html.j2
{% extends 'base.html.j2' %}


{% block content %}
<div class="container text-center mb-5 mt-5">
    <span class="title"><h1>{% block title %} The {{ customer.name }} Detail Page {% endblock %}</h1></span>
</div>

    {% include "customer/_customer_navbar.html.j2" %}

<div class="row mt-5">
  <div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
        <div class="card-header text-center">
            <h5><b>Name & Address</b></h5>
        </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>Name:</b> {{ customer.name }}</li>
            <li class="list-group-item"><b>Street:</b> {{ customer.addresses[0].street }}</li>
            <li class="list-group-item"><b>City:</b> {{ customer.addresses[0].city }}</li>
            <li class="list-group-item"><b>State:</b> {{ customer.addresses[0].state }}</li>
            <li class="list-group-item"><b>Zip:</b> {{ customer.addresses[0].zip }}</li>
        </ul>
      </div>
    </div>
  </div>
  {# Second card #}
  <div class="col-sm-6">
    <div class="card">
        <div class="card-header text-center">
            <h5><b>Contact</b></h5>
        </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>Phone Number:</b> {{ customer.phone_numbers[0].phone_number }}</li>
            <li class="list-group-item"><b>Email:</b> {{ customer.emails[0].email }}</li>
        </ul>
      </div>
    </div>
  </div>
{# End Row #}
</div>


<div class="container text-center mt-5">
    <a href="{{ url_for('customer.edit', Id=customer.id) }}" class="btn btn-primary">Edit</a>
</div>


{% endblock %}

app/templates/customer/index.html.j2
{% extends "base.html.j2" %}
{% from "includes/macros.html.j2" import render_pagination %}


{% block content %}

{# Display grid wrapper #}
<div class="wrapper">


{# Page title #}
<div class="search-page-title">
    <div class="container text-center mb-5 mt-5">
        <span class="title"><h1>{% block title %} Search Customers {% endblock %}</h1></span>
    </div> 
</div>


{# New customer button. Activates modal #}
<div class="new-customer-button">
    <button type="button" class="btn btn-primary" data-route="{{ url_for('customer.add_customer')}}" 
        id="newCustomerBtn" data-bs-target="#newCustomerModal">New Customer
    </button>
</div> 


{# Modal for new customer #}
<div class="modal fade" id="newCustomerModal" tabindex="-1" role="dialog" 
    aria-labelledby="modalLabel" aria-hidden="true">

    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            {# Script loads modal content here #}
        </div>
    </div>
</div>


{# Search bar and button #}
<div class="search-input-field">
    <form action="{{ url_for('customer.search', search_tag='search_tag') }}" method="POST" class="row mb-3" novalidate>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="col-sm-4 mb-3">
            <div class="input-group">
                <input type="text" class="form-control" name="search_tag" id="search_tag" placeholder="Search By Name">
            </div>
        </div>

        <div class="col-sm-2 mb-3">
            <button type="submit" class="btn btn-primary" id="searchButton">Search</button>
        </div>

        <div class="col-sm-4 mb-3">
            <a href="{{ url_for('customer.index')}}">
                <button type="button" class="btn btn-primary" id="resetSearchButton">Reset Search</button>
            </a>
        </div>
    </form> 
</div>

{# Customer results table #}
<div class="customer-search-table">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr class="text-center">
                <th>ID</th>
                <th>Name</th>
                <th>Street</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>View</th>
                <th>Delete</th>
            </tr>
        </thead>
     <tbody>
            {% for customer in customers.items %}
                <tr class="text-center align-middle">
                    <td>{{ customer.id }}</td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.addresses[0].street }}</td>
                    <td>{{ customer.addresses[0].city }}</td>
                    <td>{{ customer.addresses[0].state }}</td>
                    <td>{{ customer.addresses[0].zip }}</td>

                    <td id="viewBtnTD">
                        <a href="{{ url_for('customer.detail', Id=customer.id)}}">
                            <button type="button" id="viewCustomerBtn" class="btn btn-primary">View</button>
                        </a>
                    </td>

                    <td id="deleteBtnTD">
                        <button type="button" class="btn btn-secondary" 
                            data-deleting="{{ url_for('customer.delete_customer', Id=customer.id)}}" 
                            id="deleteCustomerBtn" data-bs-toggle="modal" 
                            data-bs-target="#deleteCustomerModal">Delete
                        </button>
                    </td>

                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{# PAGINATION MACRO #}
<div class="pagination-table">
    <ul class="pagination justify-content-center">
        {# Endpoint passed in from route. Either, 'customer.index' or 'customer.search'. #}
        {{ render_pagination(customers, endpoint )}}
    </ul>
</div>

</div> {# End of display grid wrapper #}

{% endblock %}


<!-- Page specific Javascripts -->
{% block extra_js %}
    <script src="{{ url_for('static', filename='assets/js/inputValidation.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
{% endblock extra_js %}