app/routes/user_profile_route.py
from app import db
from app.models.user import User
from datetime import datetime
from flask import render_template, request, url_for, redirect, Blueprint
from flask_login import login_required, current_user


bp = Blueprint('user_profile', __name__)


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()

@bp.route('/<username>/')
@login_required
def user(username):
    user = db.one_or_404(db.select(User).filter_by(username=username))
    return render_template('user_profile.html.j2', user=user)

app/templates/base.html.j2
{% from "includes/macros.html.j2" import render_flash_message %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="light">

  <head>
    <!-- Title, Meta Tags, Stylesheets, Icons, Scripts to load prior to HTML/CSS -->
    {% include "includes/head.html" %}
  </head>

  <body>

    <div class="mainParentContent">
      <div class="innerParentContent">

        {% include "includes/_navbar.html.j2" %}

        <main class="container">
          {{ render_flash_message() }}

          {% include "includes/_modals.html" %}

          {% block content %}
          {% endblock %}
        </main>

      </div>
    </div>

    {% include "includes/scripts.html" %}

    <!-- Page specific Javascript to load at the end of the body -->
    {% block extra_js %}{% endblock extra_js %}

  </body>
    {% include "includes/footer.html" %}
</html>

app/templates/include_navbar.html.j2
{% from 'bootstrap5/nav.html' import render_nav_item %}


{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{{ url_for('home.index') }}">Kill-A-Watt Electrical Inc.</a>
    </div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item"><a class="nav-link" href="{{ url_for('customer.index') }}">Customers</a>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
          <li class="nav-item nav-link">
            <span class="navbar-brand me-auto">
              <p class="fs-6">
                {{ 'Logged in as: %s' % username.replace(current_user.username,"<b>{}</b>".format(current_user.username)) | safe }}
              </p>
            </span>
            
          <li class="nav-item"><a class="nav-link" href="{{ url_for('user_profile.user', username=current_user.username) }}">Profile</a>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
        {% else %}
          <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
        {% endif %}
      </ul>
  </div>
</nav>
{% endblock %}